name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test tests --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory TestResults
        continue-on-error: false

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/test_results.trx
          retention-days: 7