name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Run this job only for pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          # Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
          allow-licenses: MIT, BSD-3-Clause, Apache-2.0, ISC, MPL-2.0

  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: |
          find tests -name "*.csproj" | while read project; do
            dotnet test "$project" --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory TestResults
          done

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/test_results.trx
          retention-days: 7